# Environment Vars in Use
# $TZ : The timezone we run in. Format US/Central or America/Chicago
# $DOCKERDIR : Usually the divtools/docker dir
# $DOCKERDATADIR: Usually the /opt dir
# $HOSTNAME: defined in .env
# $GF_SECURITY_ADMIN_USER: defined in .env (default is "admin")
# $GF_SECURITY_ADMIN_PASSWORD: defined in .env
# Section Order: CIRPNVEUE

services:
  omada:
    image: mbentley/omada-controller:latest
    container_name: omada
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s    
    network_mode: host
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - TZ=US/Central
      # By default, omada uses self-signed certs, uncomment these and add a cert if NOT using a self-signed cert
      #- SSL_CERT_NAME=tls.crt
      #- SSL_KEY_NAME=tls.key      
    volumes:
      - $DOCKERDATADIR/omada/data:/opt/tplink/EAPController/data
      - $DOCKERDATADIR/omada/logs:/opt/tplink/EAPController/logs
      - $DOCKERDATADIR/omada/work:/opt/tplink/EAPController/work