services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: dashy
    # Specify restart policy
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - 8080:8080
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      ## Bind individual files/folder
      - $DOCKERDIR/appdata/dashy/conf.yml:/app/user-data/conf.yml
      # Usage: icons/<icon-name>.png
      - $DOCKERDIR/appdata/dashy/dashboard-icons/png:/app/public/item-icons/icons

      # Usage: <icon-name>.png
      - $DOCKERDIR/appdata/dashy/dashboard-icons/png:/app/public/item-icons

      - $DOCKERDIR/appdata/dashy/images:/app/public/images
      #- $DOCKERDIR/appdata/dashy/dashboard-icons/png:/app/user-data/item-icons
      
      ## Bind full user-data folder so we can use sub-page files
      #- $DOCKERDIR/appdata/dashy/user-data:/app/public/user-data
    # Set any environmental variables
    environment:
      #- NODE_ENV=production # Uncomment once you want to run in Production Mode.
      # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1400
      - GID=1400
    # traefik labels
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dashy-rtr.entrypoints=websecure"
      - "traefik.http.routers.dashy-rtr.rule=Host(`dashy.$DOMAINNAME_2`)"
      # Middlewares
      - "traefik.http.routers.dashy-rtr.middlewares=chain-basic-auth@file"
      # HTTP Services
      - "traefik.http.routers.dashy-rtr.service=dashy-svc"
      - "traefik.http.services.dashy-svc.loadbalancer.server.port=8080"
    # Configure healthchecks
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
