services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - $DOCKERDIR/appdata/dashy/conf.yml:/app/user-data/conf.yml
      - $DOCKERDIR/appdata/dashy/dashboard-icons/png:/app/public/item-icons/icons
    ports:
      - 8080:80
    # Set any environmental variables
    environment:
      #- NODE_ENV=production # Uncomment once you want to run in Production Mode.
      # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000
      - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # traefik labels
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dashy-rtr.entrypoints=websecure"
      - "traefik.http.routers.dashy-rtr.rule=Host(`dashy.$DOMAINNAME_2`)"
      # Middlewares
      - "traefik.http.routers.dashy-rtr.middlewares=chain-basic-auth@file"
      # HTTP Services
      - "traefik.http.routers.dashy-rtr.service=dashy-svc"
      - "traefik.http.services.dashy-svc.loadbalancer.server.port=8080"
    # Configure healthchecks
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
