# Environment Vars in Use
# $TZ : The timezone we run in. Format American/Chicago
# $DOCKERDIR : Usually the divtools/docker dir
# $DOCKERDATADIR : Usually the /opt dir

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    #profiles: ["core", "all"]
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "7575:7575"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDATADIR/homarr/configs:/app/data/configs
      - $DOCKERDATADIR/homarr/icons:/app/public/icons
      - $DOCKERDATADIR/homarr/data:/data
      - $DOCKERDATADIR/homarr/imgs/backgrounds:/app/public/imgs/backgrounds
    environment:
      - TZ=$TZ
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - BASE_URL="homarr.$DOMAINNAME_2"
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.rule=Host(`homarr.$DOMAINNAME_1`) || Host(`homarr.$DOMAINNAME_2`)"
      - "traefik.http.routers.portainer-rtr.tls.certresolver=dns-cloudflare"
      # HTTP Services
      - "traefik.http.routers.homarr-secure.app=homarr"
      - "traefik.http.apps.homarr.loadbalancer.server.port=7575"
