# Environment Vars in Use
# $TZ : The timezone we run in. Format American/Chicago
# $DOCKERDIR : Usually the divtools/docker dir
# $DOCKERDATADIR : Usually the /opt dir

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    #profiles: ["core", "all"]
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "7575:7575"
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDATADIR/homarr/configs:/app/data/configs
      - $DOCKERDATADIR/homarr/icons:/app/public/icons
      - $DOCKERDATADIR/homarr/data:/data
      - $DOCKERDATADIR/homarr/imgs/backgrounds:/app/public/imgs/backgrounds
    env_file:
      - $DOCKERDIR/.env        # default .env file for all systems, 
      - $DOCKERDIR/.env.host   # Host-level ENV vars, overrides .env      
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - TZ=$TZ
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - BASE_URL="homarr.$DOMAINNAME_2"
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.homarr-rtr.rule=Host(`homarr.$DOMAINNAME_1`) || Host(`homarr.$DOMAINNAME_2`)"
      - "traefik.http.routers.homarr-rtr.tls.certresolver=dns-cloudflare"
      # Middlewares
      - "traefik.http.routers.homarr-rtr.middlewares=chain-no-auth@file"      
      # HTTP Services      
      - "traefik.http.routers.homarr-rtr.service=homarr-svc"
      - "traefik.http.services.homarr-svc.loadbalancer.server.port=7575"
