http:
  routers:
    tnhl01-service-rtr:
      rule: "Host(`tnhl01.{{env "DOMAINNAME_1"}}`) || (Host(`tn1.{{env "DOMAINNAME_1"}}`) && PathPrefix(`/proxmox/tnhl01`))"
      entryPoints:
        - "websecure"
      middlewares:
        - chain-no-auth
        - strip-all-prefixes
      service: "tnhl01-service"
      tls:
        certResolver: "dns-cloudflare"
        options: tls-opts@file

  middlewares:
    strip-all-prefixes:
      replacePath:
        path: "/"
  services:
    tnhl01-service:
      loadBalancer:
        servers:
          - url: "http://192.168.9.100:8006"
