http:
  routers:
    tnhl01-service-rtr:
      rule: "Host(`tnhl01.{{env "DOMAINNAME_1"}}`) || (Host(`tn1.{{env "DOMAINNAME_1"}}`) && PathPrefix(`/proxmox/tnhl01`))"
      entryPoints:
        - "websecure"
      middlewares:
        - chain-no-auth
        - strip-proxmox-prefix
      service: "tnhl01-service"
      tls:
        certResolver: "dns-cloudflare"
        options: tls-opts@file

  middlewares:
    strip-all-paths:
      replacePathRegex:
        regex: "^/.*"
        replacement: ""
    strip-proxmox-prefix:
      stripPrefix:
        prefixes:
          - "/proxmox/tnhl01"  # Only removes this specific path prefix, so it avoids the root redirect issue

  services:
    tnhl01-service:
      loadBalancer:
        servers:
          - url: "http://192.168.9.100:8006"
