http:
  routers:
    tnhl01-service-rtr:
      rule: "Host(`tnhl01.{{env "DOMAINNAME_2"}}`)"
      entryPoints:
        - "websecure"
      #middlewares:
        #- chain-no-auth
        #- strip-proxmox-prefix
      service: "tnhl01-service"
      tls:
        certResolver: "dns-cloudflare"
        options: tls-opts@file
  services:
    tnhl01-service:
      loadBalancer:
        servers:
          # Use the Portainer Non-Secure port since we secure it from Traefik to the Internet
          - url: "http://192.168.9.100:8006"