http:
  routers:
    syncfhmtn1-service-rtr:
      rule: "Host(`sync-fhmtn1.{{env DOMAINNAME_2 }}`)"
      entryPoints:
        - "websecure"
      middlewares:
        - chain-no-auth
      #- strip-proxmox-prefix
      service: "syncfhmtn1-service"
      tls:
        certResolver: "dns-cloudflare"
        #options: tls-opts@file
  services:
    syncfhmtn1-service:
      loadBalancer:
        #passHostHeader: true
        #serversTransport: "sync-fhmtn1"
        servers:
          # Use the SyncThing Port stored in env
          - url: "https://192.168.9.85:{{env SYNCTHING_PORT }}"
  # serversTransports:
  #   sync-fhmtn1:
  #     insecureSkipVerify: true
