### TRAEFIK CONFIG FILE ###

# This is used instead of CLI commands in the docker-compose command: setting:

global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
        domains:
          - main: "${DOMAINNAME_1}"
            sans:
              - "*.${DOMAINNAME_1}"
          - main: "${DOMAINNAME_2}"
            sans:
              - "*.${DOMAINNAME_2}"
    forwardedHeaders:
      trustedIPs:
        - "${CLOUDFLARE_IPS}"
        - "${LOCAL_IPS}"

  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true

log:
  filePath: "/logs/traefik.log"
  level: DEBUG

accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100
  filters:
    statusCodes:
      - "204-299"
      - "400-499"
      - "500-599"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: "t3_proxy"
  file:
    directory: "/rules"
    watch: true

certificatesResolvers:
  dns-cloudflare:
    acme:
      storage: "/acme.json"
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: "90"
