scrape_configs: 
  # Node Exporter Hosts
  - job_name: "node" 
    scrape_interval: 15s
    static_configs: 
      - targets: 
          - "192.168.9.104:9100"
        labels:
          instance: "monitor" 
      - targets: 
          - "192.168.9.85:9100"
        labels:
          instance: "FHMTN1" 
      - targets: 
          - "192.168.9.87:9100"
        labels:
          instance: "FHM4x8" 
      - targets: 
          - "192.168.9.103:9100"
        labels:
          instance: "traefik" 
      - targets: 
          - "192.168.9.111:9100"
        labels:
          instance: "pihole" 
      - targets: 
          - "192.168.9.141:9100"
        labels:
          instance: "ubuntu-22v2" 
      - targets: 
          - "192.168.9.201:9100"
        labels:
          instance: "zdc1" 
      - targets: 
          - "192.168.9.217:9100"
        labels:
          instance: "frigate" 

  # cAdvisor Hosts
  - job_name: "cadvisor"
    scrape_interval: 10s
    static_configs: 
      - targets: 
          - "192.168.9.104:8082"
        labels:
          instance: "monitor" 
      - targets: 
          - "192.168.9.85:8082"
        labels:
          instance: "FHMTN1" 
      - targets: 
          - "192.168.9.87:8082"
        labels:
          instance: "FHM4x8" 
      - targets: 
          - "192.168.9.103:8082"
        labels:
          instance: "traefik" 
      - targets: 
          - "192.168.9.111:8082"
        labels:
          instance: "pihole" 
      - targets: 
          - "192.168.9.141:8082"
        labels:
          instance: "ubuntu-22v2" 
      - targets: 
          - "192.168.9.201:8082"
        labels:
          instance: "zdc1" 
      - targets: 
          - "192.168.9.217:8082"
        labels:
          instance: "frigate"