pageInfo:
  title: PrivateIPs
  navLinks: []
sections:
  - name: Media & Entertainment
    items: []
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    icon: fas fa-photo-video
  - name: Networking
    icon: fas fa-network-wired
    items:
      - title: OMADA SDN (monitor)
        description: OMADA NW Management SW Controller
        icon: omada.png
        url: https://192.168.9.104:8043/
        target: newtab
        statusCheck: true
        statusCheckUrl: https://192.168.9.104:8043/
        id: 0_1064_pihole
      - title: Pi-Hole
        description: DNS Ad-Blocking
        icon: pi-hole.png
        url: http://pihole/admin/login.php
        target: newtab
        statusCheck: true
        statusCheckUrl: http://192.168.9.111/admin/login.php
        id: 0_1064_pihole
      - title: Traefik
        description: Traefik Reverse Proxy
        icon: traefik.png
        url: http://192.168.9.103:8085
        target: newtab
        statusCheck: true
        id: 1_1064_traefik
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Network Monitoring
    icon: fas fa-tachometer-alt-fast
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Uptime Kuma
        description: Uptime Kuma [monitor]
        icon: uptime-kuma.png
        url: http://192.168.9.104:3001/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 0_1840_ukuma
      - title: Grafana
        description: Grafana [monitor]
        icon: grafana.png
        url: http://192.168.9.104:3000/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 0_1840_grafana
      - title: InfluxDB
        description: InfluxDB [monitor]
        icon: influxdb.png
        url: http://192.168.9.104:8086/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 1_1840_influxdb
      - title: Prometheus
        description: Prometheus [monitor]
        icon: prometheus.png
        url: http://192.168.9.104:9091/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 2_1840_prometheus
      - title: NetBox
        description: IPAM Network Config Mgmt [monitor]
        icon: netbox.png
        url: http://192.168.9.104:8080/
        target: newtab
        statusCheck: true
        id: 3_1840_netbox
  - name: Servers/VM/NW Mgmt
    icon: fas fa-monitor-heart-rate
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: TNHL01
        description: Proxmox Server TNHL01
        icon: proxmox.png
        url: https://192.168.9.100:8006/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 0_1605_tnhl01
      - title: TNHL02
        description: Proxmox Server TNHL01
        icon: proxmox.png
        url: https://192.168.9.150:8006/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 1_1605_tnhl02
      - title: TNHL03
        description: Proxmox Server TNHL03
        icon: proxmox.png
        url: https://192.168.9.160:8006/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 0_1605_tnhl03
      - title: QNAP:FHMTN1
        description: QNAP WebUI FHMTN1
        icon: qnap-alt.png
        url: http://192.168.9.85:8080/
        target: newtab
        statusCheck: true
        id: 2_1605_qnapfhmtn
      - title: QNAP:FHM4x8
        description: QNAP WebUI FHM4x8
        icon: qnap-alt.png
        url: http://192.168.9.87:8080/
        target: newtab
        statusCheck: true
        id: 3_1605_qnapfhmx
      - title: ZDC1
        description: Zentyal NW Domain Controller [TNHL01]
        icon: windows-admin-center.jpg
        url: https://192.168.9.201:8443/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 4_1605_zdc
      - title: PBS (tnhl01)
        description: Proxmox Backup Server [TNHL01]
        icon: proxmox-light.png
        url: https://192.168.9.101:8007/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 5_1605_pbstnhl
  - name: Home Control
    icon: fas fa-house-signal
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: HomeAssistant
        description: Home Assistant (tnhl02|haos)
        icon: home-assistant.png
        url: http://192.168.9.215:8123/
        target: newtab
        statusCheck: true
        id: 0_1605_haos
      - title: Frigate (217)
        description: Frigate VM (tnhl02)
        icon: frigate.png
        url: http://192.168.9.217:5000/
        target: newtab
        statusCheck: true
        id: 0_1605_frigate
      - title: Frigate:go2rtc (217)
        description: Frigate:go2rtc VM (tnhl02)
        icon: go2rtc.png
        url: http://192.168.9.217:1984/
        target: newtab
        statusCheck: true
        id: 0_1605_frigate_go2rtc

  - name: Productivity
    icon: fas fa-bookmark
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
  - name: Dashy Docs
    icon: far fa-rocket
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: GitHub
        description: Source Code, Issues and Pull Requests
        icon: fab fa-github-alt
        url: https://github.com/lissy93/dashy
        target: newtab
        id: 0_930_github
      - title: Docs
        description: Configuring & Usage Documentation
        icon: far fa-book
        url: https://dashy.to/docs
        target: newtab
        provider: Dashy.to
        statusCheck: true
        id: 1_930_docs
      - title: WalkXCode GH
        description: Dashboard Icon List
        icon: far fa-rocket
        url: https://github.com/walkxcode/dashboard-icons
        target: newtab
        id: 2_930_walkxcodegh
      - title: WalkXCode Icons
        description: Page to Display All Icons
        icon: far fa-rocket
        url: https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md
        target: newtab
        id: 3_930_walkxcodeicons
      - title: FontAwesome Icons
        description: Searchable Font Awesome Icon Library
        icon: si-fontawesome
        url: https://fontawesome.com/icons
        target: newtab
        id: 4_930_fontawesomeicons
      - title: SimpleIcons
        description: Searchable Icon Library
        icon: si-simpleicons
        url: https://simpleicons.org/
        target: newtab
        statusCheckUrl: https://simpleicons.org/
        statusCheck: true
        id: 5_930_simpleicons
      - title: Ex Conf.YML
        description: Example Config Files for Dashy
        icon: si-yaml
        url: https://gist.github.com/Lissy93/000f712a5ce98f212817d20bc16bab10
        target: newtab
        id: 6_930_exconfyml
      - title: Sub-Pages Issue
        url: https://github.com/Lissy93/dashy/issues/1258
        target: newtab
        id: 7_930_subpagesissue
  - name: Syncthing
    icon: syncthing.png
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: FHMTN1
        icon: syncthing.png
        url: https://192.168.9.85:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 0_951_fhmtn
      - title: FHM4x8
        icon: syncthing.png
        url: https://192.168.9.87:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 1_951_fhmx
      - title: TNHL01
        icon: syncthing.png
        url: https://192.168.9.100:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 2_951_tnhl01
      - title: TNHL02
        icon: syncthing.png
        url: https://192.168.9.150:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 2_951_tnhl02
      - title: TNHL03
        icon: syncthing.png
        url: https://192.168.9.160:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 2_951_tnhl03
      - title: traefik
        icon: syncthing.png
        url: https://192.168.9.103:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 3_951_traefik
      - title: monitor
        icon: syncthing.png
        url: https://192.168.9.104:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 4_951_monitor
      - title: zdc1
        icon: syncthing.png
        url: https://192.168.9.201:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 5_951_zdc
      - title: frigate
        icon: syncthing.png
        url: https://192.168.9.217:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 7_951_frigate
      - title: pihole
        icon: syncthing.png
        url: https://192.168.9.111:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 6_951_pihole
      - title: Ubuntu-22v2
        icon: syncthing.png
        url: https://192.168.9.141:8384/
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 7_951_ubuntuv
appConfig:
  cssThemes: ["nord-frost-tl"]
  theme: nord-frost
  layout: auto
  iconSize: medium
pages:
  - name: Traefik Links
    displayData:
      hideForGuests: false
    path: traefik-links.yml
