# Environment Vars in Use
# $TZ : The timezone we run in. Format American/Chicago
# $DOCKERDIR : Usually the divtools/docker dir
# $DOCKERDATADIR: Usually the /opt dir
# $HOSTNAME: defined in .env

services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: $HOSTNAME
    restart: unless-stopped
    network_mode: host # Ensures direct network access
    env_file:
      - $DOCKERDIR/.env        # default .env file for all systems, 
      - $DOCKERDIR/.env.host   # Host-level ENV vars, overrides .env    
    environment:
      - TZ=$TZ
      #- PUID=1008
      #- PGID=1008
      - PUID=0
      - PGID=0
      #- STTRACE=all # Enables detailed logging for all components

    volumes:
      # Config
      - $DOCKERDATADIR/syncthing:/var/syncthing

      # Volume Mounts for Sharing
      - $DOCKERDATADIR/divtools:/opt/divtools
      - $DOCKERDATADIR/dt_git_test:/opt/dt_git_test
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    
